apiVersion: v1
kind: Service
metadata:
  name: sheremetyevo-server-svc
  namespace: default
spec:
  selector:
    app: sheremetyevo-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30005
  type: NodePort
